import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Main {

    static Pattern mimePat,urlPat,unFetchPat;
    static HashMap<String,Integer> mimeCount;
    static List<String> unfetchedURLs;

    public static void main(String[] args) {
        final File meta = new File(args[0]);                                        //Input the path to the folder that contains dump files of CrawlDB or your crawl.
        List<String> fileName = new ArrayList<String>();                            //Donot rename the dump files
        List<String> mimeTypes = new ArrayList<String>();

        unfetchedURLs = new ArrayList<String>();
        mimeCount = new HashMap<String, Integer>();

        String filePattern = "^(part-[0-9]*)$";                                     //Regex to match the filenames that are generated by the dump of CrawlDB (Ex: part-00000)                        
        String mimePattern = "^(Content-Type=)(.*)";                                //Regex to match Mime Types
        String urlPattern = "(^http[^ ]*)";                                         //Regex to match the url
        String unFetPattern = "Status: 1 \\(db_unfetched\\)";                       //Regex to match unfetched status

        Pattern filePat = Pattern.compile(filePattern);
        urlPat = Pattern.compile(urlPattern);
        mimePat = Pattern.compile(mimePattern);
        unFetchPat = Pattern.compile(unFetPattern);

        for(final File f:meta.listFiles())                                          //Obtain the list of dump files available in the folder containing the dumped information
        {
            Matcher m = filePat.matcher(f.getName());                               //Check if the file is dump fileType
            if(m.find())
            {
                //System.out.println(m.group(0));
                fileName.add(m.group(0));                                           //Get list of all dump files.
            }

        }

        try {
            
            GetMimeTypesForFile(args[0] + fileName.get(0));                       //Get mime types for one file. Can be repeated for multiple files.
        }
        catch (IOException e)
        {
            System.err.println(e.getMessage());
        }

       // printUnfetchedURLs();                                                                  //Uncomment to print Unfetched URL's
        try {
            printMimeData();                                                                        //Prints different Mime Types and their occurances.
        }
        catch (FileNotFoundException e)
        {
            System.err.println(e.getMessage());
        }
        catch (UnsupportedEncodingException e)
        {
            System.err.println(e.getMessage());
        }
    }

    //Function to Retrive MimeTypes from the dump file
    public static void GetMimeTypesForFile(String fname) throws IOException
    {
        File file = new File(fname);                                                                //Read the file and process line by line.
        String line,nline;
        BufferedReader br = new BufferedReader(new FileReader(file));
        while((line = br.readLine()) != null) {
            Matcher m = urlPat.matcher(line.trim());
            if (m.find()) {
                nline = br.readLine();
                Matcher m1 = unFetchPat.matcher(nline);                                             //Find unfetched urls and add it to list of unfetched urls
                if (m1.find()) {
                    unfetchedURLs.add(line);
                }
            } else {
                m = mimePat.matcher(line.trim());                                                   //If mime regex is matched, insert the mime type into hashmap or if it already exists increment its frequency.
                if (m.find()) {
                    if (mimeCount.containsKey(m.group(2)))
                        mimeCount.put(m.group(2), mimeCount.get(m.group(2)) + 1);
                    else
                        mimeCount.put(m.group(2), 1);
                }

            }
        }

    }

    //Function to print unfetched urls.
    public static void printUnfetchedURLs()
    {
        for(int i=0;i<unfetchedURLs.size();i++)
            System.out.println(unfetchedURLs.get(i));
    }

    //Function to print all MimeTypes and generates JSON text based on the information for D3 Plotting
    public static void printMimeData() throws FileNotFoundException, UnsupportedEncodingException
    {
        JSONArray jsonArray = new JSONArray();                                                              //Instantiate a JsonArry array.

        System.out.println("Total of "+mimeCount.size()+" Mime Types found. They are listed below.");
        Set<String> keys = mimeCount.keySet();
        for(String s:keys) {
            System.out.println("Type: " + s + "   Files: " + mimeCount.get(s));
            JSONObject obj = new JSONObject();                                                                 //Create JSONObject with mime type and occurrance
            obj.put("type",s);
            obj.put("count",mimeCount.get(s));
            jsonArray.add(obj);                                                                                //Insert JSONObject into JSONArray    
        }

        PrintWriter writer = new PrintWriter("JSDump.json","UTF-8");                                            //Generate JSON file with the extracted information from the dump file.
        writer.println(jsonArray.toJSONString());
        writer.close();
    }
}
